### ISSUE TITLE
Crash when running `config`

### ISSUE THREAD

**Issue by kevcube** [synfinatic/aws-sso-cli#385]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.9.0 -- Copyright 2021-2022 Aaron Turner
00620eb76250dd7c4f299521730a82a87310bf40 (Homebrew) built at 2022-05-09T16:43:52+0000
```

**Describe the bug:**
Crash when running aws-sso config

```
❯ aws-sso config
✔ Backup /Users/kevin/.aws-sso/config.yaml first? Yes
Wrote: /Users/kevin/.aws-sso/config.2022-05-09-10:46:54.yaml


**********************************************************************
* Do you have questions?  Do you like reading docs?  We've got docs! *
* https://github.com/synfinatic/aws-sso-cli/blob/main/docs/config.md *
**********************************************************************

panic: interface conversion: interface {} is string, not []interface {}

goroutine 1 [running]:
main.setupWizard(0x14000687bf0, 0x1, 0x0?)
	/private/tmp/aws-sso-cli-20220509-16995-lqyvl9/aws-sso-cli-1.9.0/cmd/setup_cmd.go:129 +0x988
main.(*ConfigCmd).Run(0x1?, 0x14000687bf0)
	/private/tmp/aws-sso-cli-20220509-16995-lqyvl9/aws-sso-cli-1.9.0/cmd/setup_cmd.go:100 +0x3c0
reflect.Value.call({0x1033e8ce0?, 0x140000e9ac0?, 0x1400013da58?}, {0x10328c4fd, 0x4}, {0x140003ce6c0, 0x1, 0x102f7f0dc?})
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/reflect/value.go:556 +0x5e4
reflect.Value.Call({0x1033e8ce0?, 0x140000e9ac0?, 0x103b5c108?}, {0x140003ce6c0, 0x1, 0x1})
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/reflect/value.go:339 +0x98
github.com/alecthomas/kong.callMethod({0x10328c072, 0x3}, {0x1033f9660?, 0x140000e9ac0?, 0x3?}, {0x1033e8ce0?, 0x140000e9ac0?, 0x1?}, 0x0?)
	/Users/kevin/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/alecthomas/kong@v0.2.18/callbacks.go:97 +0x3a4
github.com/alecthomas/kong.(*Context).RunNode(0x140000e4180, 0x14000178ee0, {0x1400013dec8, 0x1, 0x1})
	/Users/kevin/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/alecthomas/kong@v0.2.18/context.go:731 +0x468
github.com/alecthomas/kong.(*Context).Run(0x1400047a000?, {0x1400013dec8?, 0x10328fb31?, 0x20?})
	/Users/kevin/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/alecthomas/kong@v0.2.18/context.go:756 +0x148
main.main()
	/private/tmp/aws-sso-cli-20220509-16995-lqyvl9/aws-sso-cli-1.9.0/cmd/main.go:188 +0x810
```

**To Reproduce:**
1. `aws-sso config`
2. crash

**Expected behavior:**

**Screenshots:**

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Version arm64

**Additional context:**

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
  Tenant:
    SSORegion: us-east-2
    StartUrl: https://d-00000000.awsapps.com/start
    DefaultRegion: us-east-2
DefaultSSO: Tenant
UrlAction: open
LogLevel: warn
HistoryLimit: 10
HistoryMinutes: 1440
ConsoleDuration: 360
```

**Comment by synfinatic** [comment]
This should fix that.  Mind giving it a try? [aws-sso.zip](https://github.com/synfinatic/aws-sso-cli/files/8653954/aws-sso.zip)

**Comment by kevcube** [comment]
@synfinatic works! thanks
