### ISSUE TITLE
v2.0.0-beta1 panic

### ISSUE THREAD

**Issue by mouchar** [synfinatic/aws-sso-cli#759]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 2.0.0-beta1 -- Copyright 2021-2023 Aaron Turner
5a29cb37d3546335d42f03c9f0c7b40cc953df98 (v2.0.0-beta1) built at 2023-11-11T17:16:14+0000
```

**Describe the bug:**
Freshly installed aws-sso. I used it before, but wanted to try a new version, esp. because better `ProfileFormat`. I started from scratch, removed the whole `$HOME/.aws-sso` dir.

**To Reproduce:**
 1. `aws-sso` - successfully went through wizard except for the last step that failed on attept to start browser (because I was running on remote host)
 2. Added `UrlAction: print` and  `SecureStore: json` to .aws-sso/config.yaml (yes I'm lazy to type passphrase on every command)
 3. `aws-sso login` - successfully passed device auth flow via printed URL and then the panic happened:
 ```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa1d850]
```
The full output is below.

**Expected behavior:**
Login stores token and updates the cache and AWS profile list.

**Screenshots:**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - CentOS 9 Stream

**Additional context:**
Traceback:
```
aws-sso login -L trace -u printurl --sts-refresh
INFO    open /home/REDACTED/.aws-sso/cache.json: no such file or directory 
WARNING Using insecure json file for SecureStore: /home/REDACTED/.aws-sso/store.json 
DEBUG   loading SSO using 10 retries and max 5sec backoff 
DEBUG   No CreateTokenResponse for Default           
TRACE   Authenticate(printurl, )                     
TRACE   reauthenticate() for Default                 
TRACE   registerClient()                             
DEBUG   Saving JSON Cache                            
TRACE   <- reauthenticate()                          
TRACE   startDeviceAuthorization() for Default       
DEBUG   Created OIDC device code for Default (expires in: 600s) 

	Verify this code in your browser: GRTP-BJHV
TRACE   <- reauthenticate()                          
TRACE   getDeviceAuthInfo()                          
TRACE   <- reauthenticate()                          
https://device.sso.us-east-1.amazonaws.com/?user_code=GRTP-BJHV
INFO    Waiting for SSO authentication...            
TRACE   createToken()                                
DEBUG   Saving JSON Cache                            
DEBUG   Checking the current active accounts vs. our cache 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa1d850]

goroutine 1 [running]:
main.(*LoginCmd).Run(0xc000039a80, 0xc0002c8000)
	github.com/synfinatic/aws-sso-cli/cmd/aws-sso/login_cmd.go:44 +0x130
reflect.Value.call({0xa9e900?, 0xc000039a80?, 0xb68360?}, {0xb69abc, 0x4}, {0xc0002b5908, 0x1, 0x0?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0xa9e900?, 0xc000039a80?, 0xaba120?}, {0xc0002b5908?, 0xb68360?, 0x0?})
	reflect/value.go:380 +0xb9
github.com/alecthomas/kong.callFunction({0xa9e900?, 0xc000039a80?, 0x0?}, 0xb6956d?)
	github.com/alecthomas/kong@v0.8.1/callbacks.go:98 +0x40b
github.com/alecthomas/kong.(*Context).RunNode(0xc000099c80, 0xc000202690, {0xc00018de08, 0x1, 0x0?})
	github.com/alecthomas/kong@v0.8.1/context.go:765 +0x810
github.com/alecthomas/kong.(*Context).Run(0xc000270620?, {0xc00018de08?, 0x0?, 0x0?})
	github.com/alecthomas/kong@v0.8.1/context.go:790 +0x132
main.main()
	github.com/synfinatic/aws-sso-cli/cmd/aws-sso/main.go:219 +0xbae
```

My humble guess is the tool can't handle missing cache file. Running `aws-sso cache` resolves this issue.

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    Default:
        SSORegion: us-east-1
        StartUrl: https://REDACTED.awsapps.com/start
ConsoleDuration: 720
UrlAction: print
LogLevel: error
SecureStore: json
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ FirstItem .AccountName (.AccountAlias | nospace) }}:{{ .RoleName }}"
FullTextSearch: true
```

**Comment by mouchar** [comment]
Unfortunately, the issue persists even with the build aws-sso-2.0.0-beta2-linux-amd64.gz you provided:

```
/tmp/aws-sso-2.0.0-beta2-linux-amd64 login -L trace -u printurl --sts-refresh
INFO    open /home/REDACTED/.aws-sso/cache.json: no such file or directory 
DEBUG   loading SSO using 10 retries and max 5sec backoff 
INFO    You are already logged in. :)                
DEBUG   Checking the current active accounts vs. our cache 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa139cf]

goroutine 1 [running]:
github.com/synfinatic/aws-sso-cli/sso.(*SSOCache).NeedsRefresh(...)
	github.com/synfinatic/aws-sso-cli/sso/cache.go:132
main.(*LoginCmd).Run(0xc00023ac80, 0xc00023f980)
	github.com/synfinatic/aws-sso-cli/cmd/aws-sso/login_cmd.go:45 +0x18f
reflect.Value.call({0xa92700?, 0xc00023ac80?, 0xb58860?}, {0xb59fac, 0x4}, {0xc0004491b8, 0x1, 0x0?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0xa92700?, 0xc00023ac80?, 0xaadce0?}, {0xc0004491b8?, 0xb58860?, 0x0?})
	reflect/value.go:380 +0xb9
github.com/alecthomas/kong.callFunction({0xa92700?, 0xc00023ac80?, 0x0?}, 0xb59a6b?)
	github.com/alecthomas/kong@v0.8.1/callbacks.go:98 +0x40b
github.com/alecthomas/kong.(*Context).RunNode(0xc00023f600, 0xc00024e690, {0xc00037fe08, 0x1, 0x0?})
	github.com/alecthomas/kong@v0.8.1/context.go:765 +0x810
github.com/alecthomas/kong.(*Context).Run(0xc00032c5b0?, {0xc00037fe08?, 0x0?, 0x0?})
	github.com/alecthomas/kong@v0.8.1/context.go:790 +0x132
main.main()
	github.com/synfinatic/aws-sso-cli/cmd/aws-sso/main.go:219 +0xbae

```

But stack trace is slightly different.

The easiest reproducer is to delete `cache.json` and run `aws-sso login`

**Comment by synfinatic** [comment]
thanks, that's helpful.

**Comment by synfinatic** [comment]
Should work now. [Uploading aws-sso-2.0.0-beta2-linux-amd64.gz…]()

**Comment by mouchar** [comment]
Confirmed, binary built from the current `v2` branch works fine and recreates the cache file if it doesn't exist. Panic doesn't happen.
